"""
-> Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then adding one more letter at a random position.

Return the letter that was added to t.
"""

from collections import Counter

class Solution:
    def findDifference(self, s: str, t: str) -> str:
        # Use Counter to count the occurrences of each character in both strings
        count_s, count_t = Counter(s), Counter(t)

        # find the character that has a different count in t compared to s
        for c in count_t:
            if c not in count_s:
                return c
            if count_s[c] < count_t[c]:
                return c
            